version: '2.3'
services:
  data:
    image: busybox
    container_name: images2karte_data
    volumes:
      - "./:/images2karte/"
  jupyterlab:
    image: shinn1r0/jupyterlab-gpu
    ports:
      - "8888:8888"
    container_name: images2karte
    runtime: nvidia
    volumes_from:
      - data
    working_dir: /images2karte
    privileged: true
    environment:
      TZ: Asia/Tokyo
    restart: unless-stopped
    command: jupyter lab
